export const genderList = [
  {id: 'KF1', label: 'Kadın (Female)', value: 'Kadın (Female)'},
  {id: 'EM1', label: 'Erkek (Male)', value: 'Erkek (Male)'},
];
export const workTypes = [
  {
    id: 'WT1',
    label: 'Öğrenci (Student)',
    value: 'Öğrenci (Student)',
  },
  {
    id: 'WT2',
    label: 'Çalışan (Worker)',
    value: 'Çalışan (Worker)',
  },
  {
    id: 'WT3',
    label: 'İşsiz (Jobless)',
    value: 'İşsiz (Jobless)',
  },
];
export const jobTypes = [
  {id: 'doc1', label: 'Doktor', value: 'doktor'},
  {id: 'eng2', label: 'Mühendis', value: 'muhendis'},
  {id: 'tea3', label: 'Öğretmen', value: 'ogretmen'},
  {id: 'law4', label: 'Avukat', value: 'avukat'},
  {id: 'dev5', label: 'Programcı', value: 'programci'},
  {id: 'des6', label: 'Grafik Tasarımcısı', value: 'grafik-tasarimci'},
  {id: 'pol7', label: 'Polis Memuru', value: 'polis-memuru'},
  {id: 'se8', label: 'Yazılım Mühendisi', value: 'yazilim-muhendisi'},
  {id: 'nur9', label: 'Hemşire', value: 'hemsire'},
  {id: 'che10', label: 'Şef', value: 'sef'},
  {id: 'acc11', label: 'Muhasebeci', value: 'muhasebeci'},
  {id: 'arc12', label: 'Mimar', value: 'mimar'},
  {id: 'teh13', label: 'Tekniker', value: 'tekniker'},
  {id: 'ph14', label: 'Eczacı', value: 'eczaci'},
  {id: 'fit15', label: 'Fitness Antrenörü', value: 'fitness-antrenoru'},
  {id: 'cha16', label: 'Aşçı', value: 'asci'},
  {id: 'psyc17', label: 'Psikolog', value: 'psikolog'},
  {id: 'eng18', label: 'Elektrik Mühendisi', value: 'elektrik-muhendisi'},
  {id: 'vet19', label: 'Veteriner', value: 'veteriner'},
  {id: 'ph20', label: 'Fizyoterapist', value: 'fizyoterapist'},
  {id: 'jo21', label: 'Giyim Tasarımcısı', value: 'giyim-tasarimcisi'},
  {id: 'po22', label: 'Postacı', value: 'postaci'},
  {id: 'ar23', label: 'Arkeolog', value: 'arkeolog'},
  {id: 'it24', label: 'Bilgisayar Teknikeri', value: 'bilgisayar-teknikeri'},
  {id: 're25', label: 'Rehber', value: 'rehber'},
  {id: 'ch26', label: 'Kimyager', value: 'kimyager'},
  {id: 'fi27', label: 'Fizikçi', value: 'fizikci'},
  {id: 'pho28', label: 'Fotoğrafçı', value: 'fotografci'},
  {id: 'tr29', label: 'Tercüman', value: 'tercuman'},
  {id: 'co30', label: 'Kuaför', value: 'kuafor'},
  {id: 'wa31', label: 'Web Geliştirici', value: 'web-gelistirici'},
  {id: 'co32', label: 'Coğrafyacı', value: 'cografyaci'},
  {id: 'nu33', label: 'Nutrisyonist', value: 'nutrisyonist'},
  {id: 'la34', label: 'Avukat Asistanı', value: 'avukat-asistani'},
  {id: 'bi35', label: 'Biyolog', value: 'biyolog'},
  {
    id: 'so36',
    label: 'Sosyal Medya Yöneticisi',
    value: 'sosyal-medya-yoneticisi',
  },
  {id: 'se37', label: 'Ses Mühendisi', value: 'ses-muhendisi'},
  {id: 're38', label: 'Reklamcı', value: 'reklamci'},
  {id: 'tr39', label: 'Trafik Polisi', value: 'trafik-polisi'},
  {id: 'zo40', label: 'Zoolog', value: 'zoolog'},
  {id: 'la41', label: 'Lavanta Tarla İşçisi', value: 'lavanta-tarla-isci'},
  {id: 'fi42', label: 'Film Yapımcısı', value: 'film-yapimcisi'},
  {id: 'se43', label: 'SEO Uzmanı', value: 'seo-uzmani'},
  {id: 'vo44', label: 'Seslendirme Sanatçısı', value: 'seslendirme-sanatcisi'},
  {id: 'ga45', label: 'Gastronom', value: 'gastronom'},
  {
    id: 'pho46',
    label: 'Fotoğraf Stüdyo Sahibi',
    value: 'fotograf-studyo-sahibi',
  },
  {id: 'co47', label: 'Community Manager', value: 'community-manager'},
  {id: 'em48', label: 'Emlak Danışmanı', value: 'emlak-danismani'},
  {id: 'so49', label: 'Sosyolog', value: 'sosyolog'},
  {
    id: 'gr50',
    label: 'Grafik Tasarım Öğretmeni',
    value: 'grafik-tasarim-ogretmeni',
  },
];
export const educationLevel = [
  {
    id: 'elementary_school',
    label: 'İlkokul',
    value: 'İlkokul',
  },
  {
    id: 'middle_school',
    label: 'Ortaokul',
    value: 'Ortaokul',
  },
  {
    id: 'high_school',
    label: 'Lise',
    value: 'Lise',
  },
  {
    id: 'associate_degree',
    label: 'Ön Lisans',
    value: 'Ön Lisans',
  },
  {
    id: 'bachelor_degree',
    label: 'Lisans',
    value: 'Lisans',
  },
  {
    id: 'master_degree',
    label: 'Yüksek Lisans',
    value: 'Yüksek Lisans',
  },
  {
    id: 'doctorate',
    label: 'Doktora',
    value: 'Doktora',
  },
];
export const graduationYear = [
  {id: 2024, label: '2024', value: '2024'},
  {id: 2023, label: '2023', value: '2023'},
  {id: 2022, label: '2022', value: '2022'},
  {id: 2021, label: '2021', value: '2021'},
  {id: 2020, label: '2020', value: '2020'},
  {id: 2019, label: '2019', value: '2019'},
  {id: 2018, label: '2018', value: '2018'},
  {id: 2017, label: '2017', value: '2017'},
  {id: 2016, label: '2016', value: '2016'},
  {id: 2015, label: '2015', value: '2015'},
  {id: 2014, label: '2014', value: '2014'},
  {id: 2013, label: '2013', value: '2013'},
  {id: 2012, label: '2012', value: '2012'},
  {id: 2011, label: '2011', value: '2011'},
  {id: 2010, label: '2010', value: '2010'},
  {id: 2009, label: '2009', value: '2009'},
  {id: 2008, label: '2008', value: '2008'},
  {id: 2007, label: '2007', value: '2007'},
  {id: 2006, label: '2006', value: '2006'},
  {id: 2005, label: '2005', value: '2005'},
  {id: 2004, label: '2004', value: '2004'},
  {id: 2003, label: '2003', value: '2003'},
  {id: 2002, label: '2002', value: '2002'},
  {id: 2001, label: '2001', value: '2001'},
  {id: 2000, label: '2000', value: '2000'},
];
export const experinceLevel = [
  {
    id: 'D1',
    label: 'Düşük',
    value: 'Düşük',
  },
  {
    id: 'O2',
    label: 'Orta',
    value: 'Orta',
  },
  {
    id: 'Y3',
    label: 'Yüksek',
    value: 'Yüksek',
  },
];
