export const genderList = [
  {id: 'KF1', label: 'Kadın', value: 'Kadın'},
  {id: 'EM1', label: 'Erkek', value: 'Erkek'},
];
export const workTypes = [
  {
    id: 'WT1',
    label: 'Öğrenci',
    value: 'Öğrenci',
  },
  {
    id: 'WT2',
    label: 'Çalışan',
    value: 'Çalışan',
  },
  {
    id: 'WT3',
    label: 'İşsiz',
    value: 'İşsiz',
  },
];
export const jobTypes = [
  {id: 'doc1', label: 'Doktor', value: 'Doktor'},
  {id: 'eng2', label: 'Mühendis', value: 'Mühendis'},
  {id: 'tea3', label: 'Öğretmen', value: 'Öğretmen'},
  {id: 'law4', label: 'Avukat', value: 'Avukat'},
  {id: 'dev5', label: 'Programcı', value: 'Programcı'},
  {id: 'des6', label: 'Grafik Tasarımcısı', value: 'Grafik Tasarımcısı'},
  {id: 'pol7', label: 'Polis Memuru', value: 'Polis Memuru'},
  {id: 'se8', label: 'Yazılım Mühendisi', value: 'Yazılım Mühendisi'},
  {id: 'nur9', label: 'Hemşire', value: 'Hemşire'},
  {id: 'che10', label: 'Şef', value: 'Şef'},
  {id: 'acc11', label: 'Muhasebeci', value: 'Muhasebeci'},
  {id: 'arc12', label: 'Mimar', value: 'Mimar'},
  {id: 'teh13', label: 'Tekniker', value: 'Tekniker'},
  {id: 'ph14', label: 'Eczacı', value: 'Eczacı'},
  {id: 'fit15', label: 'Fitness Antrenörü', value: 'Fitness Antrenörü'},
  {id: 'cha16', label: 'Aşçı', value: 'Aşçı'},
  {id: 'psyc17', label: 'Psikolog', value: 'Psikolog'},
  {id: 'eng18', label: 'Elektrik Mühendisi', value: 'Elektrik Mühendisi'},
  {id: 'vet19', label: 'Veteriner', value: 'Veteriner'},
  {id: 'ph20', label: 'Fizyoterapist', value: 'Fizyoterapist'},
  {id: 'jo21', label: 'Giyim Tasarımcısı', value: 'Giyim Tasarımcısı'},
  {id: 'po22', label: 'Postacı', value: 'Postacı'},
  {id: 'ar23', label: 'Arkeolog', value: 'Arkeolog'},
  {id: 'it24', label: 'Bilgisayar Teknikeri', value: 'Bilgisayar Teknikeri'},
  {id: 're25', label: 'Rehber', value: 'Rehber'},
  {id: 'ch26', label: 'Kimyager', value: 'Kimyager'},
  {id: 'fi27', label: 'Fizikçi', value: 'Fizikçi'},
  {id: 'pho28', label: 'Fotoğrafçı', value: 'Fotoğrafçı'},
  {id: 'tr29', label: 'Tercüman', value: 'Tercüman'},
  {id: 'co30', label: 'Kuaför', value: 'Kuaför'},
  {id: 'wa31', label: 'Web Geliştirici', value: 'Web Geliştirici'},
  {id: 'co32', label: 'Coğrafyacı', value: 'Coğrafyacı'},
  {id: 'nu33', label: 'Nutrisyonist', value: 'Nutrisyonist'},
  {id: 'la34', label: 'Avukat Asistanı', value: 'Avukat Asistanı'},
  {id: 'bi35', label: 'Biyolog', value: 'Biyolog'},
  {
    id: 'so36',
    label: 'Sosyal Medya Yöneticisi',
    value: 'Sosyal Medya Yöneticisi',
  },
  {id: 'se37', label: 'Ses Mühendisi', value: 'Ses Mühendisi'},
  {id: 're38', label: 'Reklamcı', value: 'Reklamcı'},
  {id: 'tr39', label: 'Trafik Polisi', value: 'Trafik Polisi'},
  {id: 'zo40', label: 'Zoolog', value: 'Zoolog'},
  {id: 'la41', label: 'Lavanta Tarla İşçisi', value: 'Lavanta Tarla İşçisi'},
  {id: 'fi42', label: 'Film Yapımcısı', value: 'Film Yapımcısı'},
  {id: 'se43', label: 'SEO Uzmanı', value: 'SEO Uzmanı'},
  {id: 'vo44', label: 'Seslendirme Sanatçısı', value: 'Seslendirme Sanatçısı'},
  {id: 'ga45', label: 'Gastronom', value: 'Gastronom'},
  {
    id: 'pho46',
    label: 'Fotoğraf Stüdyo Sahibi',
    value: 'Fotoğraf Stüdyo Sahibi',
  },
  {id: 'co47', label: 'Community Manager', value: 'Community Manager'},
  {id: 'em48', label: 'Emlak Danışmanı', value: 'Emlak Danışmanı'},
  {id: 'so49', label: 'Sosyolog', value: 'Sosyolog'},
  {
    id: 'gr50',
    label: 'Grafik Tasarım Öğretmeni',
    value: 'Grafik Tasarım Öğretmeni',
  },
];
export const educationLevel = [
  {
    id: 'elementary_school',
    label: 'İlkokul',
    value: 'İlkokul',
  },
  {
    id: 'middle_school',
    label: 'Ortaokul',
    value: 'Ortaokul',
  },
  {
    id: 'high_school',
    label: 'Lise',
    value: 'Lise',
  },
  {
    id: 'associate_degree',
    label: 'Ön Lisans',
    value: 'Ön Lisans',
  },
  {
    id: 'bachelor_degree',
    label: 'Lisans',
    value: 'Lisans',
  },
  {
    id: 'master_degree',
    label: 'Yüksek Lisans',
    value: 'Yüksek Lisans',
  },
  {
    id: 'doctorate',
    label: 'Doktora',
    value: 'Doktora',
  },
];
export const graduationYear = [
  {id: 2024, label: '2024', value: '2024'},
  {id: 2023, label: '2023', value: '2023'},
  {id: 2022, label: '2022', value: '2022'},
  {id: 2021, label: '2021', value: '2021'},
  {id: 2020, label: '2020', value: '2020'},
  {id: 2019, label: '2019', value: '2019'},
  {id: 2018, label: '2018', value: '2018'},
  {id: 2017, label: '2017', value: '2017'},
  {id: 2016, label: '2016', value: '2016'},
  {id: 2015, label: '2015', value: '2015'},
  {id: 2014, label: '2014', value: '2014'},
  {id: 2013, label: '2013', value: '2013'},
  {id: 2012, label: '2012', value: '2012'},
  {id: 2011, label: '2011', value: '2011'},
  {id: 2010, label: '2010', value: '2010'},
  {id: 2009, label: '2009', value: '2009'},
  {id: 2008, label: '2008', value: '2008'},
  {id: 2007, label: '2007', value: '2007'},
  {id: 2006, label: '2006', value: '2006'},
  {id: 2005, label: '2005', value: '2005'},
  {id: 2004, label: '2004', value: '2004'},
  {id: 2003, label: '2003', value: '2003'},
  {id: 2002, label: '2002', value: '2002'},
  {id: 2001, label: '2001', value: '2001'},
  {id: 2000, label: '2000', value: '2000'},
];
export const experinceLevel = [
  {
    id: 'D1',
    label: 'Düşük',
    value: 'Düşük',
  },
  {
    id: 'O2',
    label: 'Orta',
    value: 'Orta',
  },
  {
    id: 'Y3',
    label: 'Yüksek',
    value: 'Yüksek',
  },
];
export const generateExperienceScore = {
  Yüksek: 3,
  Orta: 2,
  Düşük: 1,
};
