export const genderList = [
  {id: 'KF1', label: 'Kadın (Female)', value: 'Kadın (Female)'},
  {id: 'EM1', label: 'Erkek (Male)', value: 'Erkek (Male)'},
];
export const workTypes = [
  {
    id: 'WT1',
    label: 'Öğrenci (Student)',
    value: 'Öğrenci (Student)',
  },
  {
    id: 'WT2',
    label: 'Çalışan (Worker)',
    value: 'Çalışan (Worker)',
  },
  {
    id: 'WT3',
    label: 'İşsiz (Jobless)',
    value: 'İşsiz (Jobless)',
  },
];

export const jobTypes = [
  {id: 'doc1', label: 'Doktor', value: 'doktor'},
  {id: 'eng2', label: 'Mühendis', value: 'muhendis'},
  {id: 'tea3', label: 'Öğretmen', value: 'ogretmen'},
  {id: 'law4', label: 'Avukat', value: 'avukat'},
  {id: 'dev5', label: 'Programcı', value: 'programci'},
  {id: 'des6', label: 'Grafik Tasarımcısı', value: 'grafik-tasarimci'},
  {id: 'pol7', label: 'Polis Memuru', value: 'polis-memuru'},
  {id: 'se8', label: 'Yazılım Mühendisi', value: 'yazilim-muhendisi'},
  {id: 'nur9', label: 'Hemşire', value: 'hemsire'},
  {id: 'che10', label: 'Şef', value: 'sef'},
  {id: 'acc11', label: 'Muhasebeci', value: 'muhasebeci'},
  {id: 'arc12', label: 'Mimar', value: 'mimar'},
  {id: 'teh13', label: 'Tekniker', value: 'tekniker'},
  {id: 'ph14', label: 'Eczacı', value: 'eczaci'},
  {id: 'fit15', label: 'Fitness Antrenörü', value: 'fitness-antrenoru'},
  {id: 'cha16', label: 'Aşçı', value: 'asci'},
  {id: 'psyc17', label: 'Psikolog', value: 'psikolog'},
  {id: 'eng18', label: 'Elektrik Mühendisi', value: 'elektrik-muhendisi'},
  {id: 'vet19', label: 'Veteriner', value: 'veteriner'},
  {id: 'ph20', label: 'Fizyoterapist', value: 'fizyoterapist'},
  {id: 'jo21', label: 'Giyim Tasarımcısı', value: 'giyim-tasarimcisi'},
  {id: 'po22', label: 'Postacı', value: 'postaci'},
  {id: 'ar23', label: 'Arkeolog', value: 'arkeolog'},
  {id: 'it24', label: 'Bilgisayar Teknikeri', value: 'bilgisayar-teknikeri'},
  {id: 're25', label: 'Rehber', value: 'rehber'},
  {id: 'ch26', label: 'Kimyager', value: 'kimyager'},
  {id: 'fi27', label: 'Fizikçi', value: 'fizikci'},
  {id: 'pho28', label: 'Fotoğrafçı', value: 'fotografci'},
  {id: 'tr29', label: 'Tercüman', value: 'tercuman'},
  {id: 'co30', label: 'Kuaför', value: 'kuafor'},
  {id: 'wa31', label: 'Web Geliştirici', value: 'web-gelistirici'},
  {id: 'co32', label: 'Coğrafyacı', value: 'cografyaci'},
  {id: 'nu33', label: 'Nutrisyonist', value: 'nutrisyonist'},
  {id: 'la34', label: 'Avukat Asistanı', value: 'avukat-asistani'},
  {id: 'bi35', label: 'Biyolog', value: 'biyolog'},
  {
    id: 'so36',
    label: 'Sosyal Medya Yöneticisi',
    value: 'sosyal-medya-yoneticisi',
  },
  {id: 'se37', label: 'Ses Mühendisi', value: 'ses-muhendisi'},
  {id: 're38', label: 'Reklamcı', value: 'reklamci'},
  {id: 'tr39', label: 'Trafik Polisi', value: 'trafik-polisi'},
  {id: 'zo40', label: 'Zoolog', value: 'zoolog'},
  {id: 'la41', label: 'Lavanta Tarla İşçisi', value: 'lavanta-tarla-isci'},
  {id: 'fi42', label: 'Film Yapımcısı', value: 'film-yapimcisi'},
  {id: 'se43', label: 'SEO Uzmanı', value: 'seo-uzmani'},
  {id: 'vo44', label: 'Seslendirme Sanatçısı', value: 'seslendirme-sanatcisi'},
  {id: 'ga45', label: 'Gastronom', value: 'gastronom'},
  {
    id: 'pho46',
    label: 'Fotoğraf Stüdyo Sahibi',
    value: 'fotograf-studyo-sahibi',
  },
  {id: 'co47', label: 'Community Manager', value: 'community-manager'},
  {id: 'em48', label: 'Emlak Danışmanı', value: 'emlak-danismani'},
  {id: 'so49', label: 'Sosyolog', value: 'sosyolog'},
  {
    id: 'gr50',
    label: 'Grafik Tasarım Öğretmeni',
    value: 'grafik-tasarim-ogretmeni',
  },
];
